<?xml version="1.0" encoding="utf-8"?><Database Name="TourGuideDB" Class="DataClassesTourGuideDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLExpress;Initial Catalog=TourGuideDB;Integrated Security=True" SettingsObjectName="TourGuideDAL.Properties.Settings" SettingsPropertyName="TourGuideDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="TourID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TourDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TourGuide" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsOn" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Event_Registration" Member="Registrations" ThisKey="TourID,TourDate" OtherKey="TourID,TourDate" Type="Registration" />
      <Association Name="Tour_Event" Member="Tour" ThisKey="TourID" OtherKey="TourID" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tours" Member="Tours">
    <Type Name="Tour">
      <Column Name="TourID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TourName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TourLocation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TourCategory" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TourArea" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TourDuration" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TourPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MinReg" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MaxReg" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TourDescription" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImageData" Type="System.Byte[]" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ImageMimeType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tour_Event" Member="Events" ThisKey="TourID" OtherKey="TourID" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Registrations" Member="Registrations">
    <Type Name="Registration">
      <Column Name="RegID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TourID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TourDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RegFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegBirthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="WillAttend" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsPaid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsSentEmail" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Attended" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="RegTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Event_Registration" Member="Event" ThisKey="TourID,TourDate" OtherKey="TourID,TourDate" Type="Event" IsForeignKey="true" />
      <Association Name="User_Registration" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserPassword" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserBirthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResetToken" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="salt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Registration" Member="Registrations" ThisKey="UserID" OtherKey="UserID" Type="Registration" />
    </Type>
  </Table>
</Database>